type: object
required:
  - _id
  - title
  - category
  - owner
  - area
  - instruction
  - description
  - time
  - ingredients
  - createdAt
  - updatedAt
properties:
  _id:
    type: string
    description: Recipe id
    example: 6462a8f74c3d0ddd28897fcd
  title:
    type: string
    description: Recipe name
    example: Battenberg Cake
  category:
    type: string
    description: Category name
    example: Dessert
  owner:
    type: string
    description: Recipe author ID
    example: 64c8d958249fae54bae90bb9
  area:
    type: string
    description: Origin of the recipe
    example: British
  instruction:
    type: string
    description: Preparation description
    example: Heat oven, put the cake, wait while baking
  description:
    type: string
    description: Recipe description
    example: Piece of cake
  thumb:
    type: string
    description: Path to the recipe image
    example: https://ftp.goit.study/img/so-yummy/preview/Battenberg%20Cake.jpg
  time:
    type: integer
    description: Cooking time (in minutes)
    example: 15
  ingredients:
    type: array
    description: List of recipe ingredients
    items:
      type: object
      required:
        - ingredient
        - measure
      properties:
        ingredient:
          type: string
          description: Ingredient id
          example: 68a9d93bc172cbefce0cde82
        measure:
          type: string
          description: Measures of the ingredient
          example: "100 g"
  cals:
    type: number
    description: Amount of calories
    example: 60
  createdAt:
    type: string
    format: date-time
    example: 2025-07-30T17:51:59.589+00:00
  updatedAt:
    type: string
    format: date-time
    example: 2025-07-30T17:51:59.589+00:00