type: object
required:
  - _id
  - title
  - category
  - owner
  - area
  - instruction
  - description
  - time
  - ingredients
  - createdAt
  - updatedAt
properties:
  _id:
    type: string
    description: Recipe id
    example: 68a9d93bc172cbefce0cde82
  title:
    type: string
    description: Recipe title
    example: Carbonara
  category:
    type: string
    description: Recipe category
    example: Pasta
  owner:
    type: string
    description: Owner id
    example: 68a9d93bc172cbefce0cde82
  area:
    type: string
    description: Recipe area
    example: Italian
  instruction:
    type: string
    description: Instructions to the recipe
  description:
    type: string
    description: Description of the recipe
  time:
    type: number
    description: Cooking time in minutes
    example: 60
  ingredients:
    type: array
    items:
      type: object
      required:
        - id
        - measure
      properties:
        id:
          type: string
          description: Ingredient id
          example: 68a9d93bc172cbefce0cde82
        measure:
          type: string
          description: Measures of the ingredient
  cals:
    type: number
    description: Amount of calories
    example: 60
  thumb:
    type: string
    description: Path to the recipe image
  createdAt:
    type: string
    format: date-time
    example: 2025-07-30T17:51:59.589+00:00
  updatedAt:
    type: string
    format: date-time
    example: 2025-07-30T17:51:59.589+00:00
